// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-Qd7kjXH-KaT4tnW5yYKg0lMhc1jokU',
    appId: '1:817901471261:web:fe8b036427b5a62e2ae8f4',
    messagingSenderId: '817901471261',
    projectId: 'gestionetude-2bf18',
    authDomain: 'gestionetude-2bf18.firebaseapp.com',
    storageBucket: 'gestionetude-2bf18.firebasestorage.app',
    measurementId: 'G-EWVX6N4K37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5dV9gYuzOfOwyVeKvjJXSzbf-xoWSYYs',
    appId: '1:817901471261:android:234b4e11fa3a70292ae8f4',
    messagingSenderId: '817901471261',
    projectId: 'gestionetude-2bf18',
    storageBucket: 'gestionetude-2bf18.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN-Qd7kjXH-KaT4tnW5yYKg0lMhc1jokU',
    appId: '1:817901471261:web:f46a0acdcae8e0f72ae8f4',
    messagingSenderId: '817901471261',
    projectId: 'gestionetude-2bf18',
    authDomain: 'gestionetude-2bf18.firebaseapp.com',
    storageBucket: 'gestionetude-2bf18.firebasestorage.app',
    measurementId: 'G-G9ZS6YPD5D',
  );
}
